### PR TITLE
Issue#188 Add query tests with invalid input

### LINKED ISSUE #188: Add query tests with invalid input.
**As a** developer **i want to** limit query parameters to exact patterns **so that** invalid data will not reach the persistence layer.

We need additional query tests in order to be sure, that our API returns comprehensive responces when invalid data is sent as query parameters. We also need to apply detailed format patterns and other limitations to each query parameter in openAPI specificaition according to corresponding schema limitations if necessary. Supply each parameter with accompanying description or example. Be sure to test each query parameter, as well as sorting and filtering. Keep in mind, that filter parameter is accepted in form of RSQL.

### Tasks 
1. - [ ] Create extended "valid query parameter" and "wrong query parameter" tests where they are not present.
2. - [ ] Add regex to query parameters in openAPI specification where needed. Change `description` or add `example` accordingly.
3. - [ ] Create additional exception mappers if needed.

### PR DESCRIPTION
**Pull request by likeRewca**
dev
## ZenHub

* [Main ZenHub ticket](https://app.zenhub.com/workspaces/home-project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/home/188)

## Code reviewers

- [ ] @kh0ma
- [ ] @VadymSokorenko
- [ ] @denis-litvinov
- [ ] @annaprok
- [ ] @tex1988
- [ ] @ Ilya-Ross

### Second Level Review

- [ ] @github_username

## Summary of issue

- [ ] Create extended "valid query parameter" and "wrong query parameter" tests where they are not present.
- [ ] Add regex to query parameters in openAPI specification where needed. Change description or add example accordingly.
- [ ] Create additional exception mappers if needed.

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

### CODE REVIEW

File: home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/contacts/ContactApiIT.java [hunk 1]
```diff
@@ -33,6 +33,8 @@
 
 class ContactApiIT {
 
+    private static final int BAD_REQUEST = 400;
+    private static final int NOT_FOUND = 404;
     private final ContactApi contactApi = new ContactApi(ApiClientUtil.getClient());
     private final UserApi userApi = new UserApi(ApiClientUtil.getClient());
```
Comment (tex1988) [inline home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/contacts/ContactApiIT.java]: It may be better to use Response.Status...getStatusCode() for status code constants instead of the numbers

File: home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/news/NewsApiIT.java [hunk 2]
```diff
@@ -21,6 +21,8 @@
 
 class NewsApiIT {
 
+    private static final int BAD_REQUEST = 400;
+    private static final int NOT_FOUND = 404;
     private final NewsApi newsApi = new NewsApi(ApiClientUtil.getClient());
```
Comment (tex1988) [inline home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/news/NewsApiIT.java]: The same as for ContactApiIT

File: home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/users/UserApiIT.java [hunk 3]
```diff
@@ -28,7 +27,8 @@
 
 class UserApiIT {
 
-
+    private static final int BAD_REQUEST = 400;
+    private static final int NOT_FOUND = 404;
     private final UserApi userApi = new UserApi(ApiClientUtil.getClient());
```
Comment (tex1988) [inline home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/users/UserApiIT.java:32]: It may be better to move these constants to separate class in utils package as they repeated in every test class

Comment (tex1988) [inline home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/users/UserApiIT.java:32]: The same as QueryNewsIT

**Review by tex1988 — APPROVED** [review]

File: home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/contacts/ContactApiIT.java (hunk 1 above)
Comment (likeRewca) [reply home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/contacts/ContactApiIT.java]: U meen Response.Status.BAD_REQUEST.getStatusCode() after the equal sign?

File: home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/users/UserApiIT.java (hunk 3 above)
Comment (likeRewca) [reply home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/users/UserApiIT.java:32]: it make sense

File: home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/contacts/ContactApiIT.java (hunk 1 above)
Comment (tex1988) [reply home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/contacts/ContactApiIT.java]: Yes

File: home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/news/NewsApiIT.java (hunk 2 above)
Comment (likeRewca) [reply home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/news/NewsApiIT.java]: done

File: home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/users/UserApiIT.java (hunk 3 above)
Comment (likeRewca) [reply home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/users/UserApiIT.java:32]: done

**Review by kh0ma — APPROVED** [review]

File: home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/contacts/ContactApiIT.java (hunk 1 above)
Comment (likeRewca) [reply home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/contacts/ContactApiIT.java]: done

**Review by denis-litvinov — APPROVED** [review]

**Review by IRoss-git — APPROVED** [review]

**Review by annaprok — APPROVED** [review]

**Review by VadymSokorenko — APPROVED** [review]
